# **Machine Learning Assignment**

## Importing the libaries

In [35]:
import numpy as np
import pandas as pd

## Importing the Pre-processed Dataset

In [36]:
dataset = pd.read_csv('../Data_Analytics/preprocessed_dataset.csv')

## Dropping the Age and BMI Columns

In [37]:
dataset = dataset.drop(columns=['age', 'bmi'])
dataset = dataset.drop(dataset.columns[0], axis=1)
dataset

gender  hypertension  heart_disease  work_type  Residence_type  \
0        0.5           0.0            1.0       0.50             0.0   
1        0.5           1.0            1.0       0.50             0.0   
2        0.0           0.0            0.0       0.50             1.0   
3        0.0           0.0            0.0       0.50             0.0   
4        0.0           0.0            0.0       0.50             1.0   
...      ...           ...            ...        ...             ...   
4378     0.0           1.0            0.0       0.50             1.0   
4379     0.0           0.0            0.0       0.75             1.0   
4380     0.0           0.0            0.0       0.75             0.0   
4381     0.5           0.0            0.0       0.50             0.0   
4382     0.0           0.0            0.0       0.00             1.0   

      avg_glucose_level  smoking_status  stroke  age_group  bmi_category  \
0              0.447341        0.666667     1.0   0.714286           0.2   
1              0.131825        0.666667     1.0   0.714286           0.8   
2              0.345808        0.666667     1.0   0.714286           0.0   
3              0.185188        0.000000     1.0   0.142857           0.8   
4              0.030380        0.000000     1.0   0.714286           0.0   
...                 ...             ...     ...        ...           ...   
4378           0.252113        0.666667     0.0   0.714286           0.8   
4379           0.617119        0.666667     0.0   0.714286           0.6   
4380           0.245421        0.666667     0.0   0.142857           0.2   
4381           0.978954        0.333333     0.0   0.142857           0.8   
4382           0.265586        0.000000     0.0   0.142857           0.8   

      health_risk_factor  
0                0.90625  
1                0.93750  
2                0.68750  
3                0.78125  
4                0.62500  
...                  ...  
4378             0.93750  
4379             0.50000  
4380             0.75000  
4381             0.90625  
4382             0.62500  

[4383 rows x 11 columns]

## Dependent and Independent sets

In [38]:
X = dataset.drop(columns=['stroke']).values
y = dataset['stroke'].values

## Splitting the dataset into training and testing sets

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 0)

## Balancing the dataset

In [40]:
from imblearn.over_sampling import SMOTE

smote = SMOTE()
X_train, y_train = smote.fit_resample(X_train, y_train)
X_test, y_test = smote.fit_resample(X_test, y_test)

print(f"X_train={X_train.shape}, y_train={y_train.shape}, X_test={X_test.shape}, y_test={y_test.shape}")

X_train=(5064, 10), y_train=(5064,), X_test=(3374, 10), y_test=(3374,)


## Training the Logistic Regression Classifier

In [41]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression(random_state = 0)
logistic.fit(X_train, y_train)

LogisticRegression(random_state=0)

## Training the K-Nearest Neighbors Classifier

In [42]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
knn.fit(X_train, y_train)

KNeighborsClassifier()

## Training the Random Forest Classifier

In [43]:
from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
random_forest.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

## Training the Support Vector Machine Classifier

In [44]:
from sklearn.svm import SVC
svm = SVC(kernel = 'rbf', C = 5)
svm.fit(X_train, y_train)

SVC(C=5)

## Prediciting the values in test set using Logistic Regression Classifier

In [45]:
y_pred_logistic = logistic.predict(X_test)
print(np.concatenate((y_pred_logistic.reshape(len(y_pred_logistic),1), y_test.reshape(len(y_test),1)),1))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]


## Prediciting the values in test set using K-Nearest Neighbors Classifier

In [46]:
y_pred_knn = knn.predict(X_test)
print(np.concatenate((y_pred_knn.reshape(len(y_pred_knn),1), y_test.reshape(len(y_test),1)),1))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 1.]
 [1. 1.]
 [1. 1.]]


## Prediciting the values in test set using Random Forest Classifier

In [47]:
y_pred_random_forest = random_forest.predict(X_test)
print(np.concatenate((y_pred_random_forest.reshape(len(y_pred_random_forest),1), y_test.reshape(len(y_test),1)),1))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 1.]
 [1. 1.]
 [1. 1.]]


## Prediciting the values in test set using SVM Classifier

In [48]:
y_pred_svm = svm.predict(X_test)
print(np.concatenate((y_pred_svm.reshape(len(y_pred_svm),1), y_test.reshape(len(y_test),1)),1))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [1. 1.]
 [1. 1.]
 [1. 1.]]


## Printing the Confusion Matrix and Accuracy Score for Logistic Regression Classifier

In [49]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm = confusion_matrix(y_test, y_pred_logistic)
print(f"Confusion Matrix:\n {cm}")
print()
print(f"acccuracy: {accuracy_score(y_test, y_pred_logistic)}")

Confusion Matrix:
 [[1217  470]
 [ 636 1051]]

acccuracy: 0.6721991701244814


## Printing the Confusion Matrix and Accuracy Score for K-Nearest Neighbors Classifier

In [50]:
cm = confusion_matrix(y_test, y_pred_knn)
print(f"Confusion Matrix:\n {cm}")
print()
print(f"acccuracy: {accuracy_score(y_test, y_pred_knn)}")

Confusion Matrix:
 [[1478  209]
 [1109  578]]

acccuracy: 0.6093657379964433


## Printing the Confusion Matrix and Accuracy Score for Random Forest Classifier

In [51]:
cm = confusion_matrix(y_test, y_pred_random_forest)
print(f"Confusion Matrix:\n {cm}")
print()
print(f"acccuracy: {accuracy_score(y_test, y_pred_random_forest)}")

Confusion Matrix:
 [[1649   38]
 [ 667 1020]]

acccuracy: 0.7910491997628927


## Printing the Confusion Matrix and Accuracy Score for SVM Classifier

In [52]:
cm = confusion_matrix(y_test, y_pred_svm)
print(f"Confusion Matrix:\n {cm}")
print()
print(f"acccuracy: {accuracy_score(y_test, y_pred_svm)}")

Confusion Matrix:
 [[1426  261]
 [ 913  774]]

acccuracy: 0.6520450503852994


## K-fold Cross Validation

In [53]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

def kfold_cv(classifier, n_splits=5, shuffle=True, random_state=42):
    kf = KFold(n_splits=n_splits, shuffle=shuffle, random_state=random_state)
    cv_scores = cross_val_score(classifier, X, y, cv=kf, scoring='accuracy')
    return cv_scores

### For Logistic Regression Classifier

In [54]:
logistic_cv_scores = kfold_cv(logistic)
print("Cross-validation scores:", logistic_cv_scores)
print("Mean accuracy:", np.mean(logistic_cv_scores))

Cross-validation scores: [0.95895097 0.96807298 0.96807298 0.95776256 0.96004566]
Mean accuracy: 0.9625810281001547


### For K-Nearest Neighbors Classifier

In [55]:
knn_cv_scores = kfold_cv(knn)
print("Cross-validation scores:", knn_cv_scores)
print("Mean accuracy:", np.mean(knn_cv_scores))

Cross-validation scores: [0.95667047 0.96579247 0.96237172 0.95776256 0.956621  ]
Mean accuracy: 0.9598436450539667


### For Random Forest Classifier

In [56]:
random_forest_cv_scores = kfold_cv(random_forest)
print("Cross-validation scores:", random_forest_cv_scores)
print("Mean accuracy:", np.mean(random_forest_cv_scores))

Cross-validation scores: [0.95438997 0.96237172 0.95895097 0.95205479 0.95319635]
Mean accuracy: 0.9561927596674009


### For SVM Classifier

In [57]:
svm_cv_scores = kfold_cv(svm)
print("Cross-validation scores:", svm_cv_scores)
print("Mean accuracy:", np.mean(svm_cv_scores))

Cross-validation scores: [0.95895097 0.96807298 0.96693273 0.95776256 0.96004566]
Mean accuracy: 0.962352977929117


## Hyper-parameter Tuning

### Defining the models and their parameter range values

In [58]:
models = {
    'logistic': {
        'model': LogisticRegression(random_state=0),
        'params': {
            'solver': ['lbfgs', 'liblinear'],
            'C': [1, 5, 10],
        }
    },
    'knn': {
        'model': KNeighborsClassifier(metric='minkowski'),
        'params': {
            'n_neighbors': [3, 5, 8, 10],
            'p': [1, 2, 3],
        }
    },
    'random_forest': {
        'model': RandomForestClassifier(random_state=0),
        'params': {
            'n_estimators': [1, 5, 10, 15, 25, 50, 100, 500],
            'criterion': ['gini', 'entropy', 'log_loss'],
        }
    },
    'svm': {
        'model': SVC(gamma='auto', random_state=0),
        'params': {
            'C': [1, 10, 20],
            'kernel': ['rbf', 'linear'],
        }
    },
}


### Iterating through the models and using GridSearchCV to find the best parameters for each model

In [59]:
from sklearn.model_selection import GridSearchCV

model_scores = []
for model_name, model_param in models.items():
    clf = GridSearchCV(model_param['model'], model_param['params'], cv = 5, return_train_score = False)
    clf.fit(X_train, y_train)
    model_scores.append(
        {
            'model': model_name,
            'best_score': clf.best_score_,
            'best_params': clf.best_params_,
        }
    )


models_df = pd.DataFrame(model_scores, columns=['model', 'best_score', 'best_params'])
models_df = models_df.sort_values(by = 'best_score', ascending = False)
models_df

model  best_score                                    best_params
2  random_forest    0.972357  {'criterion': 'entropy', 'n_estimators': 100}
1            knn    0.948263                     {'n_neighbors': 3, 'p': 1}
3            svm    0.835113                     {'C': 20, 'kernel': 'rbf'}
0       logistic    0.760466                {'C': 1, 'solver': 'liblinear'}

## Index of the best model specs

In [60]:
index = models_df['best_params'].first_valid_index()

## Best Model Finalization

In [61]:
final_model = RandomForestClassifier(
    n_estimators = models_df['best_params'][index]['n_estimators'], 
    criterion = models_df['best_params'][index]['criterion'], 
    random_state = 0,
)

final_model.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', random_state=0)

## Save the model to pickle file

In [62]:
import pickle

with open('final_model.pkl', 'wb') as file:
    pickle.dump(final_model, file)

## Loading the model from the pickle file

In [63]:
with open('final_model.pkl', 'rb') as file:
    loaded_model = pickle.load(file)

## Predicting the test set values using the loaded model from the pickle file

In [64]:
y_pred = loaded_model.predict(X_test)

## K-fold Cross Validation for the loaded model from the pickle file

In [65]:
loaded_model_cv_scores = kfold_cv(loaded_model)
print("Cross-validation scores:", loaded_model_cv_scores)
print("Mean accuracy:", np.mean(loaded_model_cv_scores))

Cross-validation scores: [0.95438997 0.96351197 0.95324971 0.95319635 0.95205479]
Mean accuracy: 0.9552805589832503


## Printing the Confusion Matrix and Accuracy Score of the loaded model

In [66]:
cm = confusion_matrix(y_test, y_pred)
print(f"Confusion Matrix:\n {cm}")
print()
print(f"acccuracy: {accuracy_score(y_test, y_pred)}")

Confusion Matrix:
 [[1653   34]
 [ 591 1096]]

acccuracy: 0.8147599288678127


## Classification Report

In [67]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.74      0.98      0.84      1687
         1.0       0.97      0.65      0.78      1687

    accuracy                           0.81      3374
   macro avg       0.85      0.81      0.81      3374
weighted avg       0.85      0.81      0.81      3374



## Writing predicted values to csv file

In [68]:
new_dataset = pd.DataFrame({'y_test': y_test, 'y_predicted': y_pred})
new_dataset.to_csv('predicted_values.csv')