# **Machine Learning Assignment**

## Importing the libaries

In [27]:
import numpy as np
import pandas as pd

## Importing the Pre-processed Dataset

In [28]:
dataset = pd.read_csv('../Data_Analytics/preprocessed_dataset.csv')

## Dropping the Age and BMI Colums

In [29]:
dataset = dataset.drop(columns=['age', 'bmi'])
dataset = dataset.drop(dataset.columns[0], axis=1)
dataset

gender  hypertension  heart_disease  ever_married  work_type  \
0        0.5           0.0            1.0           1.0       0.50   
1        0.5           1.0            1.0           1.0       0.50   
2        0.0           0.0            0.0           0.0       0.50   
3        0.0           0.0            0.0           1.0       0.50   
4        0.0           0.0            0.0           1.0       0.50   
...      ...           ...            ...           ...        ...   
4378     0.0           1.0            0.0           1.0       0.50   
4379     0.0           0.0            0.0           1.0       0.75   
4380     0.0           0.0            0.0           1.0       0.75   
4381     0.5           0.0            0.0           1.0       0.50   
4382     0.0           0.0            0.0           1.0       0.00   

      Residence_type  avg_glucose_level  smoking_status  stroke  age_group  \
0                0.0           0.447341        0.666667     1.0   0.714286   
1                0.0           0.131825        0.666667     1.0   0.714286   
2                1.0           0.345808        0.666667     1.0   0.714286   
3                0.0           0.185188        0.000000     1.0   0.142857   
4                1.0           0.030380        0.000000     1.0   0.714286   
...              ...                ...             ...     ...        ...   
4378             1.0           0.252113        0.666667     0.0   0.714286   
4379             1.0           0.617119        0.666667     0.0   0.714286   
4380             0.0           0.245421        0.666667     0.0   0.142857   
4381             0.0           0.978954        0.333333     0.0   0.142857   
4382             1.0           0.265586        0.000000     0.0   0.142857   

      bmi_category  health_risk_factor  
0              0.2             0.90625  
1              0.8             0.93750  
2              0.0             0.68750  
3              0.8             0.78125  
4              0.0             0.62500  
...            ...                 ...  
4378           0.8             0.93750  
4379           0.6             0.50000  
4380           0.2             0.75000  
4381           0.8             0.90625  
4382           0.8             0.62500  

[4383 rows x 12 columns]

## Dependent and Independent sets

In [30]:
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -4].values

## Splitting the dataset into training and testing sets

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state = 0)

## Training the Logistic Regression Classifier

In [32]:
from sklearn.linear_model import LogisticRegression
logistic = LogisticRegression(random_state = 0)
logistic.fit(X_train, y_train)

LogisticRegression(random_state=0)

## Training the K-Nearest Neighbors Classifier

In [33]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
knn.fit(X_train, y_train)

KNeighborsClassifier()

## Training the Random Forest Classifier

In [34]:
from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
random_forest.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

## Prediciting the values in test set using Logistic Regression Classifier

In [35]:
y_pred_logistic = logistic.predict(X_test)
print(np.concatenate((y_pred_logistic.reshape(len(y_pred_logistic),1), y_test.reshape(len(y_test),1)),1))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [1. 1.]
 [0. 0.]]


## Prediciting the values in test set using K-Nearest Neighbors Classifier

In [36]:
y_pred_knn = knn.predict(X_test)
print(np.concatenate((y_pred_knn.reshape(len(y_pred_knn),1), y_test.reshape(len(y_test),1)),1))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [1. 1.]
 [0. 0.]]


## Prediciting the values in test set using Random Forest Classifier

In [37]:
y_pred_random_forest = random_forest.predict(X_test)
print(np.concatenate((y_pred_random_forest.reshape(len(y_pred_random_forest),1), y_test.reshape(len(y_test),1)),1))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [1. 1.]
 [0. 0.]]


## Printing the Confusion Matrix and Accuracy Score for Logistic Regression Classifier

In [38]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
cm = confusion_matrix(y_test, y_pred_logistic)
print(f"Confusion Matrix:\n {cm}")
print()
print(f"acccuracy: {accuracy_score(y_test, y_pred_logistic)}")

Confusion Matrix:
 [[1687    0]
 [   0   67]]

acccuracy: 1.0


## Printing the Confusion Matrix and Accuracy Score for K-Nearest Neighbors Classifier

In [39]:
cm = confusion_matrix(y_test, y_pred_knn)
print(f"Confusion Matrix:\n {cm}")
print()
print(f"acccuracy: {accuracy_score(y_test, y_pred_knn)}")

Confusion Matrix:
 [[1687    0]
 [   2   65]]

acccuracy: 0.9988597491448119


## Printing the Confusion Matrix and Accuracy Score for Random Forest Classifier

In [40]:
cm = confusion_matrix(y_test, y_pred_random_forest)
print(f"Confusion Matrix:\n {cm}")
print()
print(f"acccuracy: {accuracy_score(y_test, y_pred_random_forest)}")

Confusion Matrix:
 [[1687    0]
 [   0   67]]

acccuracy: 1.0


## K-fold Cross Validation

In [41]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

def kfold_cv(classifier, n_splits=5, shuffle=True, random_state=42):
    kf = KFold(n_splits=n_splits, shuffle=shuffle, random_state=random_state)
    cv_scores = cross_val_score(classifier, X, y, cv=kf, scoring='accuracy')
    return cv_scores

### For Logistic Regression Classifier

In [42]:
logistic_cv_scrores = kfold_cv(logistic)
print("Cross-validation scores:", logistic_cv_scrores)
print("Mean accuracy:", np.mean(logistic_cv_scrores))

Cross-validation scores: [1. 1. 1. 1. 1.]
Mean accuracy: 1.0


### For K-Nearest Neighbors Classifier

In [43]:
knn_cv_scrores = kfold_cv(knn)
print("Cross-validation scores:", knn_cv_scrores)
print("Mean accuracy:", np.mean(knn_cv_scrores))

Cross-validation scores: [1.         1.         1.         1.         0.99885845]
Mean accuracy: 0.9997716894977169


### For Logistic Regression Classifier

In [44]:
random_forest_cv_scrores = kfold_cv(random_forest)
print("Cross-validation scores:", random_forest_cv_scrores)
print("Mean accuracy:", np.mean(random_forest_cv_scrores))

Cross-validation scores: [1. 1. 1. 1. 1.]
Mean accuracy: 1.0


## Save model to pickle file

In [45]:
import pickle

with open('logistic.pkl', 'wb') as file:
    pickle.dump(logistic, file)
    
with open('knn.pkl', 'wb') as file:
    pickle.dump(knn, file)
    
with open('random_forest.pkl', 'wb') as file:
    pickle.dump(random_forest, file)

## Loading the model from the pickle file

In [46]:
with open('knn.pkl', 'rb') as file:
    loaded_model = pickle.load(file)

## Predicting the test set values using the loaded model from the pickle file

In [47]:
y_pred = loaded_model.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [1. 1.]
 [0. 0.]]


## K-fold Cross Validation for the loaded model from the pickle file

In [48]:
loaded_model_cv_scrores = kfold_cv(loaded_model)
print("Cross-validation scores:", loaded_model_cv_scrores)
print("Mean accuracy:", np.mean(loaded_model_cv_scrores))

Cross-validation scores: [1.         1.         1.         1.         0.99885845]
Mean accuracy: 0.9997716894977169


## Classification Report

In [49]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      1687
         1.0       1.00      0.97      0.98        67

    accuracy                           1.00      1754
   macro avg       1.00      0.99      0.99      1754
weighted avg       1.00      1.00      1.00      1754



## Writing test and predicted values to csv file

In [50]:
new_dataset = pd.DataFrame({'y_test': y_test, 'y_predicted': y_pred})
new_dataset.to_csv('predicted_values.csv')